version: "2"
services:
    client:
        build: ./client
        restart: always
        ports:
            - "3000:3000"
        links:
            - server
    server:
        build: ./server
        restart: always
        ports:
            - "3001:3001"
        volumes:
            - ./server:/server
            - /server/node_modules
        depends_on:
            - mongodb
    mongodb:
        image: mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: dummyhead
            MONGO_INITDB_ROOT_PASSWORD: shopping1!
        restart: always
        container_name: mongodb
        volumes:
            - ./data-node:/data/db
        ports:
            - 27017:27017